# Generated by Django 2.2.24 on 2021-07-19 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='表名')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wbsNb', models.CharField(max_length=255, verbose_name='WBS/WP编号')),
                ('description', models.CharField(max_length=255, verbose_name='任务内容')),
                ('projectType', models.CharField(max_length=255, verbose_name='型号')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, verbose_name='团队'),
        ),
        migrations.AlterField(
            model_name='team',
            name='peopleNb',
            field=models.IntegerField(verbose_name='人数'),
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peopleNb', models.IntegerField(verbose_name='人数')),
                ('workHours', models.IntegerField(verbose_name='工时')),
                ('taskDescription', models.CharField(max_length=255, verbose_name='任务说明')),
                ('startTime', models.DateField(verbose_name='开始时间')),
                ('endTime', models.DateField(verbose_name='结束时间')),
                ('otherDepartement', models.CharField(max_length=255, verbose_name='承接部门')),
                ('formName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.FormName')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Team')),
                ('wbsNb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Task')),
            ],
        ),
    ]
