# Generated by Django 2.2.24 on 2021-08-11 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210719_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='formname',
            name='days',
            field=models.IntegerField(default=0, verbose_name='工作日'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='formName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.FormName', verbose_name='表名'),
        ),
        migrations.AlterField(
            model_name='info',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Team', verbose_name='团队'),
        ),
        migrations.AlterField(
            model_name='info',
            name='wbsNb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Task', verbose_name='WBS编号'),
        ),
    ]
