# Generated by Django 2.2.24 on 2021-08-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210811_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='remark',
            field=models.CharField(blank=True, max_length=255, verbose_name='备注'),
        ),
    ]
