# Generated by Django 2.2.24 on 2021-08-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210811_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='wbsNb',
            field=models.CharField(max_length=255, unique=True, verbose_name='WBS/WP编号'),
        ),
    ]
